---
- name: LOG | Check ensure including configuration file for logging
  ansible.builtin.lineinfile:
    path: "{{ bind_conf }}"
    line: 'include "{{ bind_conf }}.logging";'
    state: present
  notify: Restart BIND

- name: LOG | Check ensure {{ bind_log_dir }}
  ansible.builtin.file:
    path: "{{ bind_log_dir }}"
    state: directory
    owner: bind
    mode: '0755'

- name: LOG | Check ensure {{ bind_log }}
  ansible.builtin.file:
    path: "{{ bind_log }}"
    state: touch
    owner: bind
    mode: '0644'
  changed_when: false

- name: LOG | Create link to /var/log/named.log
  ansible.builtin.file:
    src: "{{ bind_log }}"
    dest: "/var/log/named.log"
    state: link
    owner: bind

- name: LOG | Setting up a log file
  ansible.builtin.template:
    src: "log/named.conf.logging.j2"
    dest: "{{ bind_conf }}.logging"
    owner: root
    group: root
    mode: "0644"
  notify: Restart BIND
