---
- name: named | Preparation before deploy named server
  ansible.builtin.include_tasks: named-prepare.yml

- name: named | Configuring the DNS master server
  ansible.builtin.include_tasks: named-master.yml
  when: inventory_hostname in groups.named_masters

- name: named | Configuring the DNS slave server
  ansible.builtin.include_tasks: named-slave.yml
  when:
    - groups.named_slaves is defined
    - inventory_hostname in groups.named_slaves

- name: named | Configuring logging
  ansible.builtin.include_tasks: named-log.yml
  when: named_self_log
