---
- name: CHECK CONFIGURATION NAMED
  ansible.builtin.command: named-checkconf {{ named_conf }}

- name: RECONFIGURATION NAMED
  ansible.builtin.command: rndc reconfig

- name: RELOAD NAMED
  ansible.builtin.command: rndc reload

- name: RESTART NAMED
  ansible.builtin.service:
    name: "{{ named_service }}"
    state: restarted
    enabled: true
